// Default coordinates set to interurban campus
let userLat = 48.49103113795146;
let userLong = -123.41514114992222;

async function getUserCoords() {
    return new Promise((resolve, reject) => {
        if (!navigator.geolocation) {
            reject({ userLat, userLong });
        }

        navigator.geolocation.getCurrentPosition(
            // success function
            (position) => {
                userLat = position.coords.latitude;
                userLong = position.coords.longitude;
                resolve({ userLat, userLong })
            },
            // error function - defaults to interurban
            () => {
                reject({ userLat, userLong });
            }
        );
    });
}

async function getPorts() {
    const response = await fetch("public/ports.json");
    if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
    }
    const ports = await response.json();
    return ports;
}

async function getVessels() {
    const response = await fetch("public/vessels.json");
    if (!response.ok) {
        throw new Error(`Error: ${response.statusText}`);
    }
    const vessels = await response.json();
    return vessels;
}

async function getWeatherData(latitude, longitude) {
    // not my api key
    // note to self: if you do start using your own use a proxy server or something (before you commit)
    const API_KEY = "408910547897fd9d7029410128827a6d";
    const UNITS = "metric";

    const URL = `https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&units=${UNITS}&appid=${API_KEY}`;

    try {
        const response = await fetch(URL);

        if (!response.ok) {
            throw new Error(`Error: ${response.statusText}`);
        }

        const data = await response.json();

        return data;
    } catch (e) {
        console.error(`An error occurred while fetching weather data: ${e}`);
    }
}

// I used leaflet's PosAnimation: https://leafletjs.com/reference.html#posanimation
async function runBoatAnimation(latlngs, map) {
    const boatIcon = L.divIcon({
        html: `<i class="fa-solid fa-ship text-danger" style="font-size: 1.5rem"></i>`,
        className: ""
    });
    const boat = L.marker([latlngs[0].lat, latlngs[0].lng], { icon: boatIcon }).addTo(map);
    const fx = new L.PosAnimation();

    // used to ensure each PosAnimation runs one at a time
    const moveBoatToPos = (latlng) => {
        return new Promise((resolve, reject) => {
            try {
                const pos = map.latLngToLayerPoint(latlng);
                fx.run(boat._icon, pos, 2); // run the animation
                fx.once('end', resolve); // resolve the promise
            } catch (e) {
                reject(e); // reject with error
            }
        });
    };

    for (let i = 1; i < latlngs.length; i++) {
        await moveBoatToPos(latlngs[i]);
    }
}

async function loadMap() {
    const { userLat, userLong } = await getUserCoords();
    const ports = await getPorts();
    const vessels = await getVessels();

    let tripStarted = false; // used to keep track of if a user has started a trip for controlling state of marker popups
    let latlngsForTrip = []; // used to keep track of marker coords (used to draw leaflet polyline)
    let tripPolyline = null;
    let stops = [] // used to keep track of markers that are generated by clicking on ocean
    let tripDistance = 0;

    var map = L.map('map', {
        center: [userLat, userLong],
        zoom: 4,
    });

    // Add the tile layer
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    // Add a marker at Interurban or user location on load
    const userLocIcon = L.divIcon({
        html: `<i class="fa-solid fa-location-dot text-success" style="font-size: 1.5rem"></i>`,
        className: "", // remove leaflet stylings
        iconSize: [24, 24], // 24px x 24px --- 24px ~= 1.5rem
        iconAnchor: [12, 24] // sets the icon position to the middle top (since the marker is a long shape)
    });
    L.marker([userLat, userLong], { icon: userLocIcon }).addTo(map).bindPopup("You are here!");

    // Add markers at all ports
    // Using Font Awesome icons w/ Bootstrap styling for markers
    const portIcon = L.divIcon({
        html: '<i class="fa-solid fa-anchor text-primary" style="font-size: 1.5rem;"></i>',
        className: "",
        iconSize: [24, 24],
        iconAnchor: [12, 24] // sets the icon position to the middle top (since the anchor is also a long shape)
    });
    for (const port of ports) {
        L.marker([port.coordinates[0], port.coordinates[1]], { icon: portIcon }).addTo(map).bindPopup(() => {
            const disabledStartBtn = tripStarted ? "disabled" : "";
            const disabledAddStopBtn = tripStarted ? "" : "disabled";
            const disabledEndBtn = tripStarted ? "" : "disabled";

            return `
                <h5>${port.name}</h5>
                <div id="weather">Loading weather...</div>
                <button type="button" id="startTripBtn" class="btn btn-primary" ${disabledStartBtn}>Start Trip</button>
                <button type="button" id="addStopBtn" class="btn btn-primary" ${disabledAddStopBtn}>Add Stop</button>
                <button type="button" id="endTripBtn" class="btn btn-primary" ${disabledEndBtn}>End Trip</button>
            `;
        });
    }

    // Add event listeners to popup start and end trip buttons
    // have to add an event listener to detect when popups open first, because popups are added to the dom only when they are opened (i think)
    map.on("popupopen", (e) => {
        const popup = e.popup.getElement();
        const markerLatlng = e.popup._latlng;
        const startTripBtn = $(popup).find("#startTripBtn");
        const addStopBtn = $(popup).find("#addStopBtn");
        const endTripBtn = $(popup).find("#endTripBtn");

        // Async IIFE from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/async_function#async_iife
        // Add weather data to popup
        (async () => {
            const weatherData = await getWeatherData(markerLatlng.lat, markerLatlng.lng);
            $(popup).find("#weather").html(`
                <div class="d-flex">
                    <div id="weatherLeft"><img src="https://openweathermap.org/img/wn/${weatherData.weather[0].icon}.png"></div>
                    <div id"weatherRight" class="d-flex flex-column justify-content-center align-items-center">
                        ${weatherData.main.temp} &deg;C 
                        <br>
                        ${weatherData.weather[0].main}
                    </div>
                </div>
                `);
        })();

        startTripBtn.on("click", () => {
            latlngsForTrip = []; // empty array from previous trip
            if (tripPolyline) { tripPolyline.setLatLngs([]); } // reset polyline
            tripDistance = 0; // reset distance
            for (const stop of stops) { // remove stop markers
                stop.remove();
            }
            $("#distance").remove(); // remove distance displayed from previous trip (if it's there)
            $("#capableVessels").remove(); // remove list of capable vessels 
            tripStarted = true;
            startTripBtn.prop("disabled", true);
            addStopBtn.prop("disabled", false);
            endTripBtn.prop("disabled", false);
            latlngsForTrip.push(markerLatlng);
            tripPolyline = L.polyline(latlngsForTrip, { color: "red" }).addTo(map);
        });

        addStopBtn.on("click", () => {
            latlngsForTrip.push(markerLatlng);
            tripPolyline.setLatLngs(latlngsForTrip);
            tripDistance += map.distance(latlngsForTrip[latlngsForTrip.length - 2], latlngsForTrip[latlngsForTrip.length - 1]);
        });

        endTripBtn.on("click", () => {
            tripStarted = false;
            startTripBtn.prop("disabled", false);
            addStopBtn.prop("disabled", true);
            endTripBtn.prop("disabled", true);
            latlngsForTrip.push(markerLatlng);
            tripPolyline.setLatLngs(latlngsForTrip);
            runBoatAnimation(latlngsForTrip, map);
            tripDistance += map.distance(latlngsForTrip[latlngsForTrip.length - 2], latlngsForTrip[latlngsForTrip.length - 1]);

            // load vessels capable of completing trip on page
            let capableVessels = [];
            const tripDistanceInMiles = tripDistance * 0.000621371;
            for (const vessel of vessels) {
                const maxDistanceInMiles = vessel.max_travel_distance_nautical_miles;
                if (maxDistanceInMiles == "Unlimited" || maxDistanceInMiles >= tripDistanceInMiles) {
                    capableVessels.push(vessel);
                }
            }

            // determine if its raining at any of the trips markers
            // (i know joe said just to do start and stop points but that didn't make sense to me)
            // then reload the map with trip details
            let tripDetails = null;
            (async () => {
                let raining = false;
                for (const latlng of latlngsForTrip) {
                    const weatherData = await getWeatherData(latlng.lat, latlng.lng);
                    if (weatherData.weather[0].main === "Rain") {
                        raining = true;
                        break;
                    }
                }
                tripDetails = { tripDistance: tripDistanceInMiles, isRaining: raining };
                loadBoatCatalog(capableVessels, tripDetails);
            })();
        });
    });


    // Load and duplicate water polygons //
    // This stuff is where Joe differentiates the land and sea. DON'T Change this Stuff //
    // Unless you dont want it to work.
    let waterPolygons;
    // Duplicating the land and sea over 3 sets of world maps
    function duplicateWaterPolygons(original) {
        const offsets = [-360, 0, 360];
        const allFeatures = [];

        for (const offset of offsets) {
            const wrapped = JSON.parse(JSON.stringify(original));
            for (const feature of wrapped.features) {
                const geom = feature.geometry;
                if (geom.type === "Polygon") {
                    geom.coordinates = geom.coordinates.map(ring =>
                        ring.map(([lng, lat]) => [lng + offset, lat])
                    );
                } else if (geom.type === "MultiPolygon") {
                    geom.coordinates = geom.coordinates.map(polygon =>
                        polygon.map(ring =>
                            ring.map(([lng, lat]) => [lng + offset, lat])
                        )
                    );
                }
            }
            allFeatures.push(...wrapped.features);
        }

        return {
            type: "FeatureCollection",
            features: allFeatures
        };
    }
    // Fetching JSON data to make the boundaries
    fetch('public/ocean.geojson')
        .then(res => res.json())
        .then(data => {
            waterPolygons = duplicateWaterPolygons(data);
        });

    /* Click event to detect land or water. You will have to add things and change things in here
    But you won't likely want to delete  this! */
    map.on('click', function (e) {
        if (!waterPolygons) return;
        const point = turf.point([e.latlng.lng, e.latlng.lat]);
        let isInWater = null;
        for (let feature of waterPolygons.features) {
            if (turf.booleanPointInPolygon(point, feature)) {
                isInWater = true;
                break;
            }
        }
        // if its water, do something!!! Definitely delete those alerts.
        if (isInWater) {
            if (tripStarted) {
                latlngsForTrip.push(L.latLng(e.latlng.lat, e.latlng.lng));
                stops.push(L.marker([e.latlng.lat, e.latlng.lng]).addTo(map));
                tripPolyline.setLatLngs(latlngsForTrip);
                tripDistance += map.distance(latlngsForTrip[latlngsForTrip.length - 2], latlngsForTrip[latlngsForTrip.length - 1]);
            }
        } else {
            // a random thought:
            // update the map visuals so that there is only one boat icon on whatever port the trip is started at
            // the boat travels along the polyline of the trip
            // if that polyline happens to be across land... like from van to boston
            // turn the boat into a car before animating it...? this might be hard
        }
    });

    return vessels; // if this works i just might keep it, it's so stupid
}


// loads using bootstrap grid by default
function loadBoatCatalog(vessels, tripDetails) {
    let displayMode = null;

    const renderDisplayMode = (displayMode, vessels) => {
        switch (displayMode) {
            case "grid":
                displayVesselsAsGrid(vessels);
                break;
            case "row":
                displayVesselsAsRow(vessels);
                break;
            case "masonry":
                displayVesselsUsingMasonry(vessels);
                break;
            default:
                displayVesselsAsGrid(vessels);
                break;
        }
    }

    // get unique boat types
    const boatTypes = [];
    for (const vessel of vessels) {
        let typeAdded = false;
        for (const boatType of boatTypes) {
            if (vessel.type === boatType) {
                typeAdded = true;
            }
        }

        if (!typeAdded) {
            boatTypes.push(vessel.type);
        }
    }

    // not finished need to figure out how to add distance into this thing
    const calculateTotalCost = (vessel) => {
        return (vessel.crew_required * vessel.crew_cost_per_member) + vessel.base_rental_rate + vessel.fuel_surcharge + vessel.cost_per_nautical_mile;
    };

    (displayCatalogMenu = () => {
        const catalogMenu = $("#catalogMenu");
        catalogMenu.html("");

        const displayStyleDropdown = `
         <!--display style dropdown-->
        <div class="btn-group mb-3">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                aria-expanded="false">
                Select Display Style
            </button>
            <ul class="dropdown-menu">
                <li><button id="gridBtn" class="dropdown-item" type="button">Grid</button></li>
                <li><button id="rowBtn" class="dropdown-item" type="button">Row</button></li>
                <li><button id="masonryBtn" class="dropdown-item" type="button">Masonry</button></li>
            </ul>
        </div>
        `;

        const sortByDropdown = `
            <div class="btn-group mb-3">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Sort By
                </button>
                <ul class="dropdown-menu">
                    <li><button id="fastestBtn" class="dropdown-item" type="button">Fastest</button></li>
                    <li><button id="slowestBtn" class="dropdown-item" type="button">Slowest</button></li>
                    <li><button id="lowestBtn" class="dropdown-item" type="button">Lowest</button></li>
                    <li><button id="highestBtn" class="dropdown-item" type="button">Highest</button></li>
                </ul>
            </div>`;

        
        let boatTypeDropdownBtnsHtml = ``;
        for (const boatType of boatTypes) {
            boatTypeDropdownBtnsHtml += `<li><button id="${boatType.replaceAll(" ", "")}Btn" class="dropdown-item" type="button">${boatType}</button></li>`;
        }

        const boatTypeDropdown = `
            <div class="btn-group mb-3">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Choose Type
                </button>
                <ul class="dropdown-menu">
                    ${boatTypeDropdownBtnsHtml}
                    <li><button id="anyTypeBtn" class="dropdown-item" type="button">Any type</button></li>
                </ul>
            </div>
            `;

        catalogMenu.append(displayStyleDropdown);
        catalogMenu.append(sortByDropdown);
        catalogMenu.append(boatTypeDropdown);

    })();

    const catalogContent = $("#catalogContent");

    const displayVesselsAsGrid = (vessels) => {
        displayMode = "grid";
        catalogContent.html("");
        const row = `<div id="mainRow" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-4 row-cols-xxl-5 g-2 g-lg-3"></div>`;
        catalogContent.append(row);
        for (const vessel of vessels) {
            const totalCrewCost = vessel.crew_required * vessel.crew_cost_per_member;
            const totalCostForDistance = vessel.cost_per_nautical_mile * tripDetails.tripDistance;
            const fuelSurcharge = tripDetails.isRaining ? vessel.fuel_surcharge * 2 : vessel.fuel_surcharge;
            // replace boating with custom imgs in json eventually
            const boatCard = `
            <div class="col">
                <div class="card">
                    <img src="images/boat.jpeg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><b>${vessel.name}</b></h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <h5>Ship Info</h5>
                            <b>Type: </b>${vessel.type} <br>
                            <b>Length: </b>${vessel.length_meters} meters <br>
                            <b>Speed: </b>${vessel.speed_knots} knots <br>
                            <b>Max travel distance: </b>${vessel.max_travel_distance_nautical_miles} nautical miles <br>
                            <b>Cost per mile: </b>$${vessel.cost_per_nautical_mile} <br>
                            <b>Fuel surcharge: </b> $${vessel.fuel_surcharge} <br>
                            <b>Suitable for rain?: </b> ${vessel.suitable_for_rain}
                        </li>
                        <li class="list-group-item">
                            <h5>Crew Info</h5>  
                            <b>Crew required:</b> ${vessel.crew_required} members <br>
                            <b>Cost per member:</b> $${vessel.crew_cost_per_member}/member
                        </li>
                        <li class="list-group-item">
                            <h5>Cost Breakdown</h5> 
                            <b>Base rate: </b>$${vessel.base_rental_rate} <br>
                            <b>Cost of crew: </b> $${totalCrewCost}<br>
                            <b>Cost per mile * current trip distance: </b> $${totalCostForDistance} <br>
                            <b>Total fuel surcharge (2x if raining): </b>$${fuelSurcharge} <br>
                            <b>Total cost of current trip: </b>$${vessel.base_rental_rate + totalCrewCost + totalCostForDistance + fuelSurcharge}
                        </li>
                    </ul>
                    <div class="card-body">
                        <button type="button" id="${vessel.name}AddToCartBtn" class="btn btn-primary">Book Trip</button>
                    </div>
                </div>
            </div>
        `;
            catalogContent.find("#mainRow").append(boatCard);
        }
    };

    const displayVesselsAsRow = (vessels) => {
        displayMode = "row";
        catalogContent.html("");
        const row = `<div id="mainRow" class="row row-cols-1 g-2 g-lg-3"></div>`;
        catalogContent.append(row);
        for (const vessel of vessels) {
            const totalCrewCost = vessel.crew_required * vessel.crew_cost_per_member;
            const totalCostForDistance = vessel.cost_per_nautical_mile * tripDetails.tripDistance;
            const fuelSurcharge = tripDetails.isRaining ? vessel.fuel_surcharge * 2 : vessel.fuel_surcharge;
            // replace boatimg with custom imgs in json eventually
            const boatCard = `
            <div class="col">
                <div class="card">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="images/boat.jpeg" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title"><b>${vessel.name}</b></h5>
                            </div>
                           
                            <div class="accordion" id="${vessel.name.replaceAll(" ", "")}Accordion">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseOne" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseOne">
                                            Ship Info
                                        </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseOne" class="accordion-collapse collapse">
                                        <div class="accordion-body">
                                            <b>Type: </b>${vessel.type} <br>
                                            <b>Length: </b>${vessel.length_meters} meters <br>
                                            <b>Speed: </b>${vessel.speed_knots} knots <br>
                                            <b>Max travel distance: </b>${vessel.max_travel_distance_nautical_miles} nautical miles <br>
                                            <b>Cost per mile: </b>$${vessel.cost_per_nautical_mile} <br>
                                            <b>Fuel surcharge: </b> $${vessel.fuel_surcharge} <br>
                                            <b>Suitable for rain?: </b> ${vessel.suitable_for_rain}
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseTwo" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseTwo">
                                        Crew Info
                                    </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseTwo" class="accordion-collapse collapse">
                                    <div class="accordion-body">
                                        <b>Crew required:</b> ${vessel.crew_required} members <br>
                                        <b>Cost per member:</b> $${vessel.crew_cost_per_member}/member
                                    </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseThree" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseThree">
                                        Cost Breakdown
                                    </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseThree" class="accordion-collapse collapse">
                                    <div class="accordion-body">
                                        <b>Base rate: </b>$${vessel.base_rental_rate} <br>
                                        <b>Cost of crew: </b> $${totalCrewCost}<br>
                                        <b>Cost per mile * current trip distance: </b> $${totalCostForDistance} <br>
                                        <b>Total fuel surcharge (2x if raining): </b>$${fuelSurcharge} <br>
                                        <b>Total cost of current trip: </b>$${vessel.base_rental_rate + totalCrewCost + totalCostForDistance + fuelSurcharge}
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <button type="button" id="${vessel.name.replaceAll(" ", "")}AddToCartBtn" class="btn btn-primary">Book Trip</button>
                            </div>
                        </div>
                    </div>    
                </div>
            </div>
        `;
            catalogContent.find("#mainRow").append(boatCard);
        }
    };

    const displayVesselsUsingMasonry = (vessels) => {


        displayMode = "masonry";
        catalogContent.html("");
        const row = `<div id="mainRow" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-4 row-cols-xxl-5 g-2 g-lg-3" data-masonry='{"percentPosition": true }'></div>`;
        catalogContent.append(row);
        for (const vessel of vessels) {
            const totalCrewCost = vessel.crew_required * vessel.crew_cost_per_member;
            const totalCostForDistance = vessel.cost_per_nautical_mile * tripDetails.tripDistance;
            const fuelSurcharge = tripDetails.isRaining ? vessel.fuel_surcharge * 2 : vessel.fuel_surcharge;

            // replace boatimg with custom imgs in json eventually
            const boatCard = `
            <div class="col">
                <div class="card">
                            <img src="images/boat.jpeg" class="img-fluid rounded-start" alt="...">
                            <div class="card-body">
                                <h5 class="card-title"><b>${vessel.name}</b></h5>
                            </div>
                           
                            <div class="accordion" id="${vessel.name.replaceAll(" ", "")}Accordion">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseOne" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseOne">
                                            Ship Info
                                        </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseOne" class="accordion-collapse collapse">
                                        <div class="accordion-body">
                                            <b>Type: </b>${vessel.type} <br>
                                            <b>Length: </b>${vessel.length_meters} meters <br>
                                            <b>Speed: </b>${vessel.speed_knots} knots <br>
                                            <b>Max travel distance: </b>${vessel.max_travel_distance_nautical_miles} nautical miles <br>
                                            <b>Cost per mile: </b>$${vessel.cost_per_nautical_mile} <br>
                                            <b>Fuel surcharge: </b> $${vessel.fuel_surcharge} <br>
                                            <b>Suitable for rain?: </b> ${vessel.suitable_for_rain}
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseTwo" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseTwo">
                                        Crew Info
                                    </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseTwo" class="accordion-collapse collapse">
                                    <div class="accordion-body">
                                        <b>Crew required:</b> ${vessel.crew_required} members <br>
                                        <b>Cost per member:</b> $${vessel.crew_cost_per_member}/member
                                    </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#${vessel.name.replaceAll(" ", "")}CollapseThree" aria-expanded="false" aria-controls="${vessel.name.replaceAll(" ", "")}CollapseThree">
                                        Cost Breakdown
                                    </button>
                                    </h2>
                                    <div id="${vessel.name.replaceAll(" ", "")}CollapseThree" class="accordion-collapse collapse">
                                    <div class="accordion-body">
                                        <b>Base rate: </b>$${vessel.base_rental_rate} <br>
                                        <b>Cost of crew: </b> $${totalCrewCost}<br>
                                        <b>Cost per mile * current trip distance: </b> $${totalCostForDistance} <br>
                                        <b>Total fuel surcharge (2x if raining): </b>$${fuelSurcharge} <br>
                                        <b>Total cost of current trip: </b>$${vessel.base_rental_rate + totalCrewCost + totalCostForDistance + fuelSurcharge}
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <button type="button" id="${vessel.name.replaceAll(" ", "")}AddToCartBtn" class="btn btn-primary">Book Trip</button>
                            </div>
                </div>
            </div>
        `;
            catalogContent.find("#mainRow").append(boatCard);
        }
    };

    // all sorting operations for now will by default use grid??? // idk how to deal with the multiple display types and sorting rn
    // oh i just figure it out
    // ill keep track of the state of the display update it in the on clicks
    // and then use it to determine which display method to use?
    // still trying to figure out how the displays and the sort will work together
    // since we will want to be able to do every sort on each display type
    // OOOOOO WE HAVE TO SORT THE VESSELS ARRAY THEN CALL THE DISPLAY FUNCTIONS DUHHHH

    let sortedVessels = vessels;

    const sortByFastest = () => {
        sortedVessels.sort((a, b) => b.speed_knots - a.speed_knots);
        renderDisplayMode(displayMode, sortedVessels);
    };

    const sortBySlowest = () => {
        sortedVessels.sort((a, b) => a.speed_knots - b.speed_knots);
        renderDisplayMode(displayMode, sortedVessels);
    };

    const sortByLowest = () => {
        // I'm so sorry this is disgusting and I am lazy
        sortedVessels.sort((a, b) => (a.base_rental_rate + (a.crew_required * a.crew_cost_per_member) + (a.cost_per_nautical_mile * tripDetails.tripDistance) + (tripDetails.isRaining ? a.fuel_surcharge * 2 : a.fuel_surcharge)) - (b.base_rental_rate + (b.crew_required * b.crew_cost_per_member) + (b.cost_per_nautical_mile * tripDetails.tripDistance) + (tripDetails.isRaining ? b.fuel_surcharge * 2 : b.fuel_surcharge)));
        renderDisplayMode(displayMode, sortedVessels);
    };

    const sortByHighest = () => {
        sortedVessels.sort((a, b) => (b.base_rental_rate + (b.crew_required * b.crew_cost_per_member) + (b.cost_per_nautical_mile * tripDetails.tripDistance) + (tripDetails.isRaining ? b.fuel_surcharge * 2 : b.fuel_surcharge)) - (a.base_rental_rate + (a.crew_required * a.crew_cost_per_member) + (a.cost_per_nautical_mile * tripDetails.tripDistance) + (tripDetails.isRaining ? a.fuel_surcharge * 2 : a.fuel_surcharge)));
        renderDisplayMode(displayMode, sortedVessels);
    };

    const sortByType = (type) => {
        // vessels with matching type in new arr
        // redisplay those vessels

        sortedVessels = [];
        for (const vessel of vessels) { 
            if (vessel.type == type) {
                sortedVessels.push(vessel);
            }
        }

        renderDisplayMode(displayMode, sortedVessels);
    };

    const sortByAnyType = () => {
        sortedVessels = vessels;
        renderDisplayMode(displayMode, sortedVessels);
    };

    // default calls
    displayVesselsAsGrid(vessels);


    $("#gridBtn").on("click", () => {displayVesselsAsGrid(sortedVessels)});
    $("#rowBtn").on("click", () => {displayVesselsAsRow(sortedVessels)});
    $("#masonryBtn").on("click", () => {displayVesselsUsingMasonry(sortedVessels)});

    $("#fastestBtn").on("click", sortByFastest);
    $("#slowestBtn").on("click", sortBySlowest);

    $("#lowestBtn").on("click", sortByLowest);
    $("#highestBtn").on("click", sortByHighest);

    $("#anyTypeBtn").on("click", sortByAnyType);
    for (const boatType of boatTypes) {
        $("#" + boatType.replaceAll(" ", "") + "Btn").on("click", () => {sortByType(boatType)});
    }
}

// loadMap returns the object with the json data for the boats
(async () => {
    loadBoatCatalog(await loadMap(), { tripDistance: 0, isRaining: false });
})();
